version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend  # Caminho para o Dockerfile do backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # Caminho para o Dockerfile do frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
